import type { Config } from 'eslint/config'
import { commaDangleOptions, lineAroundCommentOptions, paddingLineBetweenStatements } from './constants'

export const stylisticRules: Config['rules'] = {
    '@stylistic/array-bracket-newline': ['error', 'consistent'],
    '@stylistic/array-element-newline': ['error', 'consistent'],
    '@stylistic/brace-style': ['error', '1tbs', { allowSingleLine: false }],
    '@stylistic/comma-dangle': ['error', commaDangleOptions],
    '@stylistic/function-call-argument-newline': ['error', 'consistent'],
    '@stylistic/function-call-spacing': 'error',
    '@stylistic/function-paren-newline': ['error', 'multiline-arguments'],
    '@stylistic/generator-star-spacing': ['error', 'both'],
    '@stylistic/implicit-arrow-linebreak': 'error',
    '@stylistic/jsx-child-element-spacing': 'off',
    '@stylistic/jsx-newline': 'off',
    '@stylistic/jsx-props-no-multi-spaces': 'off',
    '@stylistic/jsx-quotes': ['error', 'prefer-double'],
    '@stylistic/jsx-self-closing-comp': 'off',
    '@stylistic/jsx-sort-props': 'off',
    '@stylistic/linebreak-style': ['error', 'unix'],
    '@stylistic/lines-around-comment': ['error', lineAroundCommentOptions],
    '@stylistic/max-len': 'off',
    '@stylistic/multiline-ternary': ['error', 'never'],
    '@stylistic/newline-per-chained-call': 'off',
    '@stylistic/no-confusing-arrow': 'error',
    '@stylistic/no-extra-semi': 'error',
    '@stylistic/nonblock-statement-body-position': ['error', 'below'],
    '@stylistic/object-curly-newline': ['error', { consistent: true, multiline: true }],
    '@stylistic/object-property-newline': ['error', { allowAllPropertiesOnSameLine: true }],
    '@stylistic/one-var-declaration-per-line': 'off',
    '@stylistic/operator-linebreak': ['error', 'after'],
    '@stylistic/padding-line-between-statements': ['error', ...paddingLineBetweenStatements],
    '@stylistic/quote-props': ['error', 'consistent'],
    '@stylistic/semi-style': 'error',
    '@stylistic/spaced-comment': ['error', 'always', { line: { markers: ['/'] } }],
    '@stylistic/switch-colon-spacing': 'error',
    '@stylistic/wrap-regex': 'off',
    '@stylistic/yield-star-spacing': ['error', 'both'],
}
