export const jsoncFiles = [
    '**/[jt]sconfig.json',
    '**/[jt]sconfig.*.json',
    '**/.vscode/*.json',
    '**/turbo.json',
]

export const packageJsonSortOrder = [
    'publisher',
    'name',
    'displayName',
    'type',
    'version',
    'private',
    'packageManager',
    'description',
    'author',
    'contributors',
    'license',
    'funding',
    'homepage',
    'repository',
    'bugs',
    'keywords',
    'categories',
    'sideEffects',
    'imports',
    'exports',
    'main',
    'module',
    'unpkg',
    'jsdelivr',
    'types',
    'typesVersions',
    'bin',
    'icon',
    'files',
    'engines',
    'activationEvents',
    'contributes',
    'scripts',
    'peerDependencies',
    'peerDependenciesMeta',
    'dependencies',
    'optionalDependencies',
    'devDependencies',
    'pnpm',
    'overrides',
    'resolutions',
    'husky',
    'simple-git-hooks',
    'lint-staged',
    'eslintConfig',
]

export const exportsSortOrder = [
    'types',
    'import',
    'require',
    'default',
]

export const gitHooksSortOrder = [
    'pre-commit',
    'prepare-commit-msg',
    'commit-msg',
    'post-commit',
    'pre-rebase',
    'post-rewrite',
    'post-checkout',
    'post-merge',
    'pre-push',
    'pre-auto-gc',
]

export const tsconfigRootSortOrder = [
    'extends',
    'compilerOptions',
    'references',
    'files',
    'include',
    'exclude',
]

export const compilerOptionsSortOrder = [
    /* Projects */
    'incremental',
    'composite',
    'tsBuildInfoFile',
    'disableSourceOfProjectReferenceRedirect',
    'disableSolutionSearching',
    'disableReferencedProjectLoad',

    /* Language and Environment */
    'target',
    'jsx',
    'jsxFactory',
    'jsxFragmentFactory',
    'jsxImportSource',
    'lib',
    'moduleDetection',
    'noLib',
    'reactNamespace',
    'useDefineForClassFields',
    'emitDecoratorMetadata',
    'experimentalDecorators',
    'libReplacement',

    /* Modules */
    'baseUrl',
    'rootDir',
    'rootDirs',
    'customConditions',
    'module',
    'moduleResolution',
    'moduleSuffixes',
    'noResolve',
    'paths',
    'resolveJsonModule',
    'resolvePackageJsonExports',
    'resolvePackageJsonImports',
    'typeRoots',
    'types',
    'allowArbitraryExtensions',
    'allowImportingTsExtensions',
    'allowUmdGlobalAccess',

    /* JavaScript Support */
    'allowJs',
    'checkJs',
    'maxNodeModuleJsDepth',

    /* Type Checking */
    'strict',
    'strictBindCallApply',
    'strictFunctionTypes',
    'strictNullChecks',
    'strictPropertyInitialization',
    'allowUnreachableCode',
    'allowUnusedLabels',
    'alwaysStrict',
    'exactOptionalPropertyTypes',
    'noFallthroughCasesInSwitch',
    'noImplicitAny',
    'noImplicitOverride',
    'noImplicitReturns',
    'noImplicitThis',
    'noPropertyAccessFromIndexSignature',
    'noUncheckedIndexedAccess',
    'noUnusedLocals',
    'noUnusedParameters',
    'useUnknownInCatchVariables',

    /* Emit */
    'declaration',
    'declarationDir',
    'declarationMap',
    'downlevelIteration',
    'emitBOM',
    'emitDeclarationOnly',
    'importHelpers',
    'importsNotUsedAsValues',
    'inlineSourceMap',
    'inlineSources',
    'mapRoot',
    'newLine',
    'noEmit',
    'noEmitHelpers',
    'noEmitOnError',
    'outDir',
    'outFile',
    'preserveConstEnums',
    'preserveValueImports',
    'removeComments',
    'sourceMap',
    'sourceRoot',
    'stripInternal',

    /* Interop Constraints */
    'allowSyntheticDefaultImports',
    'esModuleInterop',
    'forceConsistentCasingInFileNames',
    'isolatedDeclarations',
    'isolatedModules',
    'preserveSymlinks',
    'verbatimModuleSyntax',
    'erasableSyntaxOnly',

    /* Completeness */
    'skipDefaultLibCheck',
    'skipLibCheck',
]
