import type { Config } from 'eslint/config'

export const javascriptRules: Config['rules'] = {
    'accessor-pairs': ['error', { enforceForClassMembers: true, setWithoutGet: true }],
    'array-callback-return': 'error',
    'block-scoped-var': 'error',
    'curly': ['error', 'all'],
    'default-case-last': 'error',
    'default-param-last': 'off',
    'eqeqeq': ['error', 'smart'],
    'grouped-accessor-pairs': 'error',
    'logical-assignment-operators': 'error',
    'new-cap': 'off',
    'no-alert': 'error',
    'no-array-constructor': 'error',
    'no-caller': 'error',
    'no-console': ['error', { allow: ['warn', 'error'] }],
    'no-constructor-return': 'error',
    'no-else-return': ['error', { allowElseIf: true }],
    'no-empty': ['error', { allowEmptyCatch: true }],
    'no-eval': 'error',
    'no-extend-native': 'error',
    'no-extra-bind': 'error',
    'no-extra-label': 'error',
    'no-fallthrough': ['error', { allowEmptyCase: true, commentPattern: String.raw`break[\s\w]*omitted` }],
    'no-implied-eval': 'error',
    'no-iterator': 'error',
    'no-label-var': 'error',
    'no-labels': 'error',
    'no-lone-blocks': 'error',
    'no-multi-str': 'error',
    'no-new': 'error',
    'no-new-func': 'error',
    'no-new-wrappers': 'error',
    'no-octal-escape': 'error',
    'no-promise-executor-return': 'error',
    'no-proto': 'error',
    'no-redeclare': ['error', { builtinGlobals: false }],
    'no-restricted-globals': ['error', { message: 'Use `globalThis` instead.', name: 'global' }, { message: 'Use `globalThis` instead.', name: 'self' }],
    'no-restricted-properties': [
        'error',
        { message: 'Use `Object.defineProperty` instead.', property: '__defineGetter__' },
        { message: 'Use `Object.defineProperty` instead.', property: '__defineSetter__' },
        { message: 'Use `Object.getOwnPropertyDescriptor` instead.', property: '__lookupGetter__' },
        { message: 'Use `Object.getOwnPropertyDescriptor` instead.', property: '__lookupSetter__' },
    ],
    'no-restricted-syntax': ['error', 'LabeledStatement', 'TSEnumDeclaration[const=true]', 'TSExportAssignment'],
    'no-self-compare': 'error',
    'no-sequences': 'error',
    'no-template-curly-in-string': 'error',
    'no-throw-literal': 'error',
    'no-undef-init': 'error',
    'no-unmodified-loop-condition': 'error',
    'no-unneeded-ternary': ['error', { defaultAssignment: false }],
    'no-unreachable-loop': 'error',
    'no-unused-expressions': ['error', { allowShortCircuit: true, allowTaggedTemplates: true, allowTernary: true }],
    'no-use-before-define': ['error', { classes: false, functions: false, variables: true }],
    'no-useless-call': 'error',
    'no-useless-computed-key': ['error', { enforceForClassMembers: true }],
    'no-useless-concat': 'error',
    'no-useless-constructor': 'error',
    'no-useless-rename': 'error',
    'no-useless-return': 'error',
    'no-var': 'error',
    'object-shorthand': ['error', 'properties', { avoidQuotes: true }],
    'one-var': ['error', { initialized: 'never' }],
    'operator-assignment': 'error',
    'prefer-arrow-callback': 'error',
    'prefer-const': ['error', { destructuring: 'all', ignoreReadBeforeAssign: true }],
    'prefer-exponentiation-operator': 'error',
    'prefer-object-has-own': 'error',
    'prefer-promise-reject-errors': ['error', { allowEmptyReject: true }],
    'prefer-regex-literals': ['error', { disallowRedundantWrapping: true }],
    'prefer-rest-params': 'error',
    'prefer-spread': 'error',
    'prefer-template': 'error',
    'sort-imports': ['error', { ignoreDeclarationSort: true }],
    'symbol-description': 'error',
    'unicode-bom': 'error',
    'yoda': 'error',

    // import-x
    'import-x/consistent-type-specifier-style': 'off',
    'import-x/first': 'error',
    'import-x/newline-after-import': ['error', { count: 1 }],
    'import-x/no-absolute-path': 'error',
    'import-x/no-cycle': ['error', { maxDepth: 3 }],
    'import-x/no-duplicates': ['error', { 'prefer-inline': true }],
    'import-x/no-empty-named-blocks': 'error',
    'import-x/no-mutable-exports': 'error',
    'import-x/no-named-as-default': 'off',
    'import-x/no-named-as-default-member': 'off',
    'import-x/no-named-default': 'error',
    'import-x/no-self-import': 'error',
    'import-x/no-unresolved': 'off',
    'import-x/no-useless-path-segments': 'error',
    'import-x/no-webpack-loader-syntax': 'error',
    'import-x/order': 'error',

    // unused-imports
    'no-unused-vars': 'off',
    'unused-imports/no-unused-imports': 'error',
    'unused-imports/no-unused-vars': ['error', { args: 'after-used', argsIgnorePattern: '^_', vars: 'all', varsIgnorePattern: '^_' }],

    // antfu
    'antfu/consistent-chaining': 'error',
    'antfu/consistent-list-newline': 'error',
    'antfu/if-newline': 'error',
    'antfu/import-dedupe': 'error',
    'antfu/no-import-dist': 'error',
    'antfu/no-import-node-modules-by-path': 'error',
}

export const javascriptRulesInEditor: Config['rules'] = {
    'prefer-const': 'warn',
    'unused-imports/no-unused-imports': 'warn',
}
