import type { Config } from 'eslint/config'

export const vueOverrideRules: Config['rules'] = {
    'vue/attributes-order': ['error', { alphabetical: true }],
    'vue/block-lang': ['error', { script: { lang: 'ts' } }],
    'vue/block-order': ['error', { order: ['script', 'template', 'style'] }],
    'vue/block-tag-newline': ['error', { maxEmptyLines: 1, multiline: 'always', singleline: 'consistent' }],
    'vue/component-api-style': ['error', ['script-setup', 'composition']],
    'vue/component-name-in-template-casing': 'error',
    'vue/component-options-name-casing': 'error',
    'vue/custom-event-name-casing': ['error', 'kebab-case'],
    'vue/define-emits-declaration': 'error',
    'vue/define-macros-order': ['error', { order: ['defineOptions', 'defineProps', 'defineEmits', 'defineSlots'] }],
    'vue/define-props-declaration': 'error',
    'vue/define-props-destructuring': ['error', { destructure: 'only-when-assigned' }],
    'vue/html-button-has-type': 'error',
    'vue/html-comment-content-newline': 'error',
    'vue/html-comment-content-spacing': 'error',
    'vue/html-self-closing': ['error', { html: { component: 'always', normal: 'never', void: 'always' }, math: 'always', svg: 'always' }],
    'vue/match-component-file-name': ['error', { extensions: ['.jsx', '.tsx', '.vue'] }],
    'vue/match-component-import-name': 'error',
    'vue/multi-word-component-names': 'off',
    'vue/next-tick-style': 'error',
    'vue/no-duplicate-attr-inheritance': 'off',
    'vue/no-empty-component-block': 'error',
    'vue/no-extra-parens': ['error', 'functions'],
    'vue/no-import-compiler-macros': 'error',
    'vue/no-multiple-objects-in-class': 'error',
    'vue/no-potential-component-option-typo': ['error', { presets: ['all'] }],
    'vue/no-ref-object-reactivity-loss': 'error',
    'vue/no-required-prop-with-default': ['error', { autofix: true }],
    'vue/no-restricted-v-bind': ['error', '/^v-/'],
    'vue/no-setup-props-reactivity-loss': 'off',
    'vue/no-template-target-blank': 'error',
    'vue/no-this-in-before-route-enter': 'error',
    'vue/no-undef-components': 'error',
    'vue/no-unused-emit-declarations': 'error',
    'vue/no-unused-refs': 'error',
    'vue/no-unused-vars': ['error', { ignorePattern: '^_' }],
    'vue/no-use-v-else-with-v-for': 'error',
    'vue/no-useless-mustaches': 'error',
    'vue/no-useless-v-bind': 'error',
    'vue/no-v-html': 'off',
    'vue/no-v-text': 'error',
    'vue/padding-line-between-blocks': 'error',
    'vue/padding-lines-in-component-definition': 'error',
    'vue/prefer-define-options': 'error',
    'vue/prefer-prop-type-boolean-first': 'error',
    'vue/prefer-separate-static-class': 'error',
    'vue/prefer-true-attribute-shorthand': 'error',
    'vue/require-default-prop': 'off',
    'vue/require-direct-export': 'error',
    'vue/require-emit-validator': 'error',
    'vue/require-explicit-slots': 'error',
    'vue/require-macro-variable-name': 'error',
    'vue/require-name-property': 'error',
    'vue/require-typed-object-prop': 'error',
    'vue/require-typed-ref': 'error',
    'vue/singleline-html-element-content-newline': 'off',
    'vue/v-bind-style': ['error', 'shorthand', { sameNameShorthand: 'always' }],
    'vue/v-for-delimiter-style': 'error',
    'vue/v-on-handler-style': ['error', ['method', 'inline-function']],
    'vue/valid-v-bind': 'off',
}
