import type { Config } from 'eslint/config'

export const sonarjsOverrideRules: Config['rules'] = {
    'sonarjs/arguments-order': 'off',
    'sonarjs/assertions-in-tests': 'off',
    'sonarjs/block-scoped-var': 'off',
    'sonarjs/code-eval': 'off',
    'sonarjs/cognitive-complexity': 'off',
    'sonarjs/cyclomatic-complexity': ['error', { threshold: 15 }],
    'sonarjs/deprecation': 'off',
    'sonarjs/fixme-tag': 'error',
    'sonarjs/function-return-type': 'off',
    'sonarjs/hashing': 'off',
    'sonarjs/max-switch-cases': ['error', 30],
    'sonarjs/no-array-delete': 'off',
    'sonarjs/no-async-constructor': 'off',
    'sonarjs/no-clear-text-protocols': 'off',
    'sonarjs/no-collapsible-if': 'error',
    'sonarjs/no-commented-code': 'error',
    'sonarjs/no-duplicate-in-composite': 'error',
    'sonarjs/no-duplicate-string': 'off',
    'sonarjs/no-fallthrough': 'off',
    'sonarjs/no-for-in-iterable': 'error',
    'sonarjs/no-global-this': 'off',
    'sonarjs/no-hardcoded-ip': 'error',
    'sonarjs/no-hardcoded-secrets': 'off',
    'sonarjs/no-implicit-dependencies': 'off',
    'sonarjs/no-inconsistent-returns': 'off',
    'sonarjs/no-incorrect-string-concat': 'error',
    'sonarjs/no-invariant-returns': 'off',
    'sonarjs/no-labels': 'off',
    'sonarjs/no-nested-assignment': 'off',
    'sonarjs/no-nested-conditional': 'off',
    'sonarjs/no-nested-functions': 'off',
    'sonarjs/no-nested-switch': 'error',
    'sonarjs/no-nested-template-literals': 'off',
    'sonarjs/no-os-command-from-path': 'off',
    'sonarjs/no-primitive-wrappers': 'off',
    'sonarjs/no-return-type-any': 'error',
    'sonarjs/no-selector-parameter': 'off',
    'sonarjs/no-small-switch': 'error',
    'sonarjs/no-unused-vars': 'off',
    'sonarjs/non-number-in-arithmetic-expression': 'error',
    'sonarjs/prefer-default-last': 'off',
    'sonarjs/prefer-immediate-return': 'error',
    'sonarjs/prefer-regexp-exec': 'off',
    'sonarjs/pseudo-random': 'off',
    'sonarjs/redundant-type-aliases': 'off',
    'sonarjs/strings-comparison': 'error',
    'sonarjs/todo-tag': 'off',
    'sonarjs/unicode-aware-regex': 'off',
    'sonarjs/unused-import': 'off',
    'sonarjs/updated-loop-counter': 'off',
    'sonarjs/values-not-convertible-to-numbers': 'error',
}
