import type { Config } from 'eslint/config'

export const unicornOverrideRules: Config['rules'] = {
    'unicorn/consistent-function-scoping': ['error', { checkArrowFunctions: false }],
    'unicorn/custom-error-definition': 'off',
    'unicorn/filename-case': ['error', { cases: { kebabCase: true, pascalCase: true }, ignore: [String.raw`.*\.md$`] }],
    'unicorn/import-style': 'off',
    'unicorn/new-for-builtins': 'off',
    'unicorn/no-array-callback-reference': 'off',
    'unicorn/no-array-method-this-argument': 'off',
    'unicorn/no-array-push-push': 'off',
    'unicorn/no-array-reduce': 'off',
    'unicorn/no-await-expression-member': 'off',
    'unicorn/no-empty-file': 'off',
    'unicorn/no-null': 'off',
    'unicorn/no-process-exit': 'off',
    'unicorn/no-this-assignment': 'off',
    'unicorn/no-useless-undefined': ['error', { checkArguments: false }],
    'unicorn/prefer-array-find': 'off',
    'unicorn/prefer-at': 'error',
    'unicorn/prefer-event-target': 'off',
    'unicorn/prefer-export-from': ['error', { ignoreUsedVariables: true }],
    'unicorn/prefer-includes': 'off',
    'unicorn/prefer-math-min-max': 'off',
    'unicorn/prefer-module': 'off',
    'unicorn/prefer-regexp-test': 'off',
    'unicorn/prefer-string-starts-ends-with': 'off',
    'unicorn/prefer-structured-clone': 'error',
    'unicorn/prefer-ternary': ['error', 'only-single-line'],
    'unicorn/prefer-top-level-await': 'off',
    'unicorn/prevent-abbreviations': 'off',
    'unicorn/require-number-to-fixed-digits-argument': 'off',
    'unicorn/switch-case-braces': ['error', 'avoid'],
}
